// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AISettings {
    "scope": string;
    "useGlobal": boolean;
    "chat": ModelConfig;
    "embedding": EmbeddingConfig;
    "vision": VisionConfig;

    /** Creates a new AISettings instance. */
    constructor($$source: Partial<AISettings> = {}) {
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("useGlobal" in $$source)) {
            this["useGlobal"] = false;
        }
        if (!("chat" in $$source)) {
            this["chat"] = (new ModelConfig());
        }
        if (!("embedding" in $$source)) {
            this["embedding"] = (new EmbeddingConfig());
        }
        if (!("vision" in $$source)) {
            this["vision"] = (new VisionConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AISettings {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chat" in $$parsedSource) {
            $$parsedSource["chat"] = $$createField2_0($$parsedSource["chat"]);
        }
        if ("embedding" in $$parsedSource) {
            $$parsedSource["embedding"] = $$createField3_0($$parsedSource["embedding"]);
        }
        if ("vision" in $$parsedSource) {
            $$parsedSource["vision"] = $$createField4_0($$parsedSource["vision"]);
        }
        return new AISettings($$parsedSource as Partial<AISettings>);
    }
}

export class Chapter {
    "id": string;
    "book_id": string;
    "chapter_index": number;
    "title": string;
    "file_path": string;
    "paragraph_count": number;
    "created_at": string;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("paragraph_count" in $$source)) {
            this["paragraph_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

export class EmbeddingConfig {
    "provider": string;
    "model": string;
    "apiKey": string;
    "baseUrl": string;
    "dimensions": number;

    /** Creates a new EmbeddingConfig instance. */
    constructor($$source: Partial<EmbeddingConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmbeddingConfig($$parsedSource as Partial<EmbeddingConfig>);
    }
}

export class GetBookByIDRow {
    "id": string;
    "title": string;
    "author": string;
    "description": string;
    "publisher": string;
    "language": string;
    "cover_path": string;
    "source_file_path": string;
    "total_chapters": number;
    "total_paragraphs": number;
    "created_at": string;
    "updated_at": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new GetBookByIDRow instance. */
    constructor($$source: Partial<GetBookByIDRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("cover_path" in $$source)) {
            this["cover_path"] = "";
        }
        if (!("source_file_path" in $$source)) {
            this["source_file_path"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }
        if (!("total_paragraphs" in $$source)) {
            this["total_paragraphs"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetBookByIDRow instance from a string or object.
     */
    static createFrom($$source: any = {}): GetBookByIDRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetBookByIDRow($$parsedSource as Partial<GetBookByIDRow>);
    }
}

export class ListBooksRow {
    "id": string;
    "title": string;
    "author": string;
    "description": string;
    "publisher": string;
    "language": string;
    "cover_path": string;
    "source_file_path": string;
    "total_chapters": number;
    "total_paragraphs": number;
    "created_at": string;
    "updated_at": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new ListBooksRow instance. */
    constructor($$source: Partial<ListBooksRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("cover_path" in $$source)) {
            this["cover_path"] = "";
        }
        if (!("source_file_path" in $$source)) {
            this["source_file_path"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }
        if (!("total_paragraphs" in $$source)) {
            this["total_paragraphs"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListBooksRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ListBooksRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListBooksRow($$parsedSource as Partial<ListBooksRow>);
    }
}

export class ListChapterStatsByBookRow {
    "chapter_index": number;
    "title": string;
    "paragraph_count": number;
    "total_visits": any;
    "visited_paragraphs": number;

    /** Creates a new ListChapterStatsByBookRow instance. */
    constructor($$source: Partial<ListChapterStatsByBookRow> = {}) {
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("paragraph_count" in $$source)) {
            this["paragraph_count"] = 0;
        }
        if (!("total_visits" in $$source)) {
            this["total_visits"] = null;
        }
        if (!("visited_paragraphs" in $$source)) {
            this["visited_paragraphs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListChapterStatsByBookRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ListChapterStatsByBookRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListChapterStatsByBookRow($$parsedSource as Partial<ListChapterStatsByBookRow>);
    }
}

export class ModelConfig {
    "provider": string;
    "model": string;
    "apiKey": string;
    "baseUrl": string;
    "temperature": number;
    "maxTokens": number;

    /** Creates a new ModelConfig instance. */
    constructor($$source: Partial<ModelConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelConfig($$parsedSource as Partial<ModelConfig>);
    }
}

export class Paragraph {
    "id": string;
    "book_id": string;
    "chapter_index": number;
    "paragraph_index": number;
    "file_path": string;
    "content_preview": string;
    "created_at": string;

    /** Creates a new Paragraph instance. */
    constructor($$source: Partial<Paragraph> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("paragraph_index" in $$source)) {
            this["paragraph_index"] = 0;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("content_preview" in $$source)) {
            this["content_preview"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Paragraph instance from a string or object.
     */
    static createFrom($$source: any = {}): Paragraph {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Paragraph($$parsedSource as Partial<Paragraph>);
    }
}

export class ParagraphStat {
    "book_id": string;
    "chapter_index": number;
    "paragraph_index": number;
    "visit_count": number;
    "is_skipped": number;
    "custom_font_family": string;
    "custom_font_size": number;
    "updated_at": string;

    /** Creates a new ParagraphStat instance. */
    constructor($$source: Partial<ParagraphStat> = {}) {
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("paragraph_index" in $$source)) {
            this["paragraph_index"] = 0;
        }
        if (!("visit_count" in $$source)) {
            this["visit_count"] = 0;
        }
        if (!("is_skipped" in $$source)) {
            this["is_skipped"] = 0;
        }
        if (!("custom_font_family" in $$source)) {
            this["custom_font_family"] = "";
        }
        if (!("custom_font_size" in $$source)) {
            this["custom_font_size"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParagraphStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ParagraphStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParagraphStat($$parsedSource as Partial<ParagraphStat>);
    }
}

export class Prompt {
    "id": string;
    "name": string;
    "description": string;
    "icon": string;
    "color_palette": string;
    "system_prompt": string;
    "user_prompt": string;
    "provider": string;
    "model": string;
    "temperature": number;
    "max_tokens": number;
    "is_builtin": number;
    "is_enabled": number;
    "sort_order": number;
    "scope": string;
    "book_id": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Prompt instance. */
    constructor($$source: Partial<Prompt> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("color_palette" in $$source)) {
            this["color_palette"] = "";
        }
        if (!("system_prompt" in $$source)) {
            this["system_prompt"] = "";
        }
        if (!("user_prompt" in $$source)) {
            this["user_prompt"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("max_tokens" in $$source)) {
            this["max_tokens"] = 0;
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = 0;
        }
        if (!("is_enabled" in $$source)) {
            this["is_enabled"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prompt instance from a string or object.
     */
    static createFrom($$source: any = {}): Prompt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Prompt($$parsedSource as Partial<Prompt>);
    }
}

export class ReadingProgress {
    "book_id": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new ReadingProgress instance. */
    constructor($$source: Partial<ReadingProgress> = {}) {
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadingProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadingProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadingProgress($$parsedSource as Partial<ReadingProgress>);
    }
}

export class ReadingSettings {
    "scope": string;
    "fontFamily": string;
    "fontSize": number;
    "lineHeight": string;
    "maxWidth": string;
    "textAlign": string;

    /** Creates a new ReadingSettings instance. */
    constructor($$source: Partial<ReadingSettings> = {}) {
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            this["lineHeight"] = "";
        }
        if (!("maxWidth" in $$source)) {
            this["maxWidth"] = "";
        }
        if (!("textAlign" in $$source)) {
            this["textAlign"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadingSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadingSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadingSettings($$parsedSource as Partial<ReadingSettings>);
    }
}

export class SentenceAnnotation {
    "sentence_hash": string;
    "book_id": string;
    "chapter_index": number;
    "paragraph_index": number;
    "is_bookmarked": number;
    "highlight_color": string;
    "upvotes_count": number;
    "emoji_reactions": string;
    "updated_at": string;

    /** Creates a new SentenceAnnotation instance. */
    constructor($$source: Partial<SentenceAnnotation> = {}) {
        if (!("sentence_hash" in $$source)) {
            this["sentence_hash"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("paragraph_index" in $$source)) {
            this["paragraph_index"] = 0;
        }
        if (!("is_bookmarked" in $$source)) {
            this["is_bookmarked"] = 0;
        }
        if (!("highlight_color" in $$source)) {
            this["highlight_color"] = "";
        }
        if (!("upvotes_count" in $$source)) {
            this["upvotes_count"] = 0;
        }
        if (!("emoji_reactions" in $$source)) {
            this["emoji_reactions"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SentenceAnnotation instance from a string or object.
     */
    static createFrom($$source: any = {}): SentenceAnnotation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SentenceAnnotation($$parsedSource as Partial<SentenceAnnotation>);
    }
}

export class SentenceComment {
    "id": string;
    "sentence_hash": string;
    "book_id": string;
    "content": string;
    "created_at": string;

    /** Creates a new SentenceComment instance. */
    constructor($$source: Partial<SentenceComment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sentence_hash" in $$source)) {
            this["sentence_hash"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SentenceComment instance from a string or object.
     */
    static createFrom($$source: any = {}): SentenceComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SentenceComment($$parsedSource as Partial<SentenceComment>);
    }
}

export class VisionConfig {
    "provider": string;
    "model": string;
    "apiKey": string;
    "baseUrl": string;

    /** Creates a new VisionConfig instance. */
    constructor($$source: Partial<VisionConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VisionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): VisionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VisionConfig($$parsedSource as Partial<VisionConfig>);
    }
}

// Private type creation functions
const $$createType0 = ModelConfig.createFrom;
const $$createType1 = EmbeddingConfig.createFrom;
const $$createType2 = VisionConfig.createFrom;
