// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Chapter {
    "id": string;
    "book_id": string;
    "chapter_index": number;
    "title": string;
    "file_path": string;
    "paragraph_count": number;
    "created_at": string;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("paragraph_count" in $$source)) {
            this["paragraph_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

export class GetBookByIDRow {
    "id": string;
    "title": string;
    "author": string;
    "description": string;
    "publisher": string;
    "language": string;
    "cover_path": string;
    "source_file_path": string;
    "total_chapters": number;
    "total_paragraphs": number;
    "created_at": string;
    "updated_at": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new GetBookByIDRow instance. */
    constructor($$source: Partial<GetBookByIDRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("cover_path" in $$source)) {
            this["cover_path"] = "";
        }
        if (!("source_file_path" in $$source)) {
            this["source_file_path"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }
        if (!("total_paragraphs" in $$source)) {
            this["total_paragraphs"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetBookByIDRow instance from a string or object.
     */
    static createFrom($$source: any = {}): GetBookByIDRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetBookByIDRow($$parsedSource as Partial<GetBookByIDRow>);
    }
}

export class ListBooksRow {
    "id": string;
    "title": string;
    "author": string;
    "description": string;
    "publisher": string;
    "language": string;
    "cover_path": string;
    "source_file_path": string;
    "total_chapters": number;
    "total_paragraphs": number;
    "created_at": string;
    "updated_at": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new ListBooksRow instance. */
    constructor($$source: Partial<ListBooksRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("cover_path" in $$source)) {
            this["cover_path"] = "";
        }
        if (!("source_file_path" in $$source)) {
            this["source_file_path"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }
        if (!("total_paragraphs" in $$source)) {
            this["total_paragraphs"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListBooksRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ListBooksRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListBooksRow($$parsedSource as Partial<ListBooksRow>);
    }
}

export class Paragraph {
    "id": string;
    "book_id": string;
    "chapter_index": number;
    "paragraph_index": number;
    "file_path": string;
    "content_preview": string;
    "created_at": string;

    /** Creates a new Paragraph instance. */
    constructor($$source: Partial<Paragraph> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("paragraph_index" in $$source)) {
            this["paragraph_index"] = 0;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("content_preview" in $$source)) {
            this["content_preview"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Paragraph instance from a string or object.
     */
    static createFrom($$source: any = {}): Paragraph {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Paragraph($$parsedSource as Partial<Paragraph>);
    }
}

export class ReadingProgress {
    "book_id": string;
    "current_chapter_index": number;
    "current_paragraph_index": number;
    "percent_complete": number;
    "last_read_at": string;

    /** Creates a new ReadingProgress instance. */
    constructor($$source: Partial<ReadingProgress> = {}) {
        if (!("book_id" in $$source)) {
            this["book_id"] = "";
        }
        if (!("current_chapter_index" in $$source)) {
            this["current_chapter_index"] = 0;
        }
        if (!("current_paragraph_index" in $$source)) {
            this["current_paragraph_index"] = 0;
        }
        if (!("percent_complete" in $$source)) {
            this["percent_complete"] = 0;
        }
        if (!("last_read_at" in $$source)) {
            this["last_read_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadingProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadingProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadingProgress($$parsedSource as Partial<ReadingProgress>);
    }
}
