// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WordDefinition represents an individual definition, its part of speech, and examples.
 */
export class WordDefinition {
    "part_of_speech": string;
    "definition": string;
    "examples": string[];

    /** Creates a new WordDefinition instance. */
    constructor($$source: Partial<WordDefinition> = {}) {
        if (!("part_of_speech" in $$source)) {
            this["part_of_speech"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }
        if (!("examples" in $$source)) {
            this["examples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WordDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): WordDefinition {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("examples" in $$parsedSource) {
            $$parsedSource["examples"] = $$createField2_0($$parsedSource["examples"]);
        }
        return new WordDefinition($$parsedSource as Partial<WordDefinition>);
    }
}

/**
 * WordEntry represents an English vocabulary lookup result.
 */
export class WordEntry {
    "word": string;
    "definitions": WordDefinition[];

    /** Creates a new WordEntry instance. */
    constructor($$source: Partial<WordEntry> = {}) {
        if (!("word" in $$source)) {
            this["word"] = "";
        }
        if (!("definitions" in $$source)) {
            this["definitions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WordEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): WordEntry {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definitions" in $$parsedSource) {
            $$parsedSource["definitions"] = $$createField1_0($$parsedSource["definitions"]);
        }
        return new WordEntry($$parsedSource as Partial<WordEntry>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = WordDefinition.createFrom;
const $$createType2 = $Create.Array($$createType1);
