// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../llm/models.js";

export function AnalyzeParagraph(text: string, analysisType: string): $CancellablePromise<string> {
    return $Call.ByID(3220602772, text, analysisType);
}

export function SetProvider(p: llm$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(3930761227, p);
}
