// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AnalyzeParagraph keeps backward-compatibility, running analysis with a prompt ID
 */
export function AnalyzeParagraph(text: string, promptID: string): $CancellablePromise<string> {
    return $Call.ByID(3220602772, text, promptID);
}

/**
 * AnalyzeParagraphWithBook executes analysis for a specific prompt ID and book context
 */
export function AnalyzeParagraphWithBook(text: string, promptID: string, bookID: string): $CancellablePromise<string> {
    return $Call.ByID(907536673, text, promptID, bookID);
}
