// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function DeleteBook(id: string): $CancellablePromise<void> {
    return $Call.ByID(2658628187, id);
}

export function GetAllBooks(): $CancellablePromise<db$0.ListBooksRow[]> {
    return $Call.ByID(167924296).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBook(id: string): $CancellablePromise<db$0.GetBookByIDRow | null> {
    return $Call.ByID(964243470, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportBook(filePath: string): $CancellablePromise<db$0.GetBookByIDRow | null> {
    return $Call.ByID(328050381, filePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SelectAndImportBook(): $CancellablePromise<db$0.GetBookByIDRow | null> {
    return $Call.ByID(360592474).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = db$0.ListBooksRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.GetBookByIDRow.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
