// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DictionaryService provides offline dictionary lookups for English vocabulary using gown.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dictionary$0 from "../dictionary/models.js";

/**
 * LookupEnglishWord queries the offline WordNet dictionary for definitions and examples.
 */
export function LookupEnglishWord(word: string): $CancellablePromise<dictionary$0.WordEntry[]> {
    return $Call.ByID(1085661898, word).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dictionary$0.WordEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
