// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export function GetChapters(bookID: string): $CancellablePromise<db$0.Chapter[]> {
    return $Call.ByID(3585073963, bookID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetParagraphContent(bookID: string, chapterIndex: number, paragraphIndex: number): $CancellablePromise<string> {
    return $Call.ByID(1207352262, bookID, chapterIndex, paragraphIndex);
}

export function GetParagraphs(bookID: string, chapterIndex: number): $CancellablePromise<db$0.Paragraph[]> {
    return $Call.ByID(1514791094, bookID, chapterIndex).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProgress(bookID: string): $CancellablePromise<db$0.ReadingProgress | null> {
    return $Call.ByID(251424062, bookID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveProgress(bookID: string, chapterIndex: number, paragraphIndex: number, percent: number): $CancellablePromise<void> {
    return $Call.ByID(169201873, bookID, chapterIndex, paragraphIndex, percent);
}

// Private type creation functions
const $$createType0 = db$0.Chapter.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.Paragraph.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = db$0.ReadingProgress.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
