// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetApiKey(): $CancellablePromise<string> {
    return $Call.ByID(682982808);
}

export function SaveApiKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(122644043, key);
}
