// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Book struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Author          string    `json:"author"`
	Description     string    `json:"description"`
	Publisher       string    `json:"publisher"`
	Language        string    `json:"language"`
	CoverPath       string    `json:"cover_path"`
	SourceFilePath  string    `json:"source_file_path"`
	TotalChapters   int64     `json:"total_chapters"`
	TotalParagraphs int64     `json:"total_paragraphs"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Chapter struct {
	ID             string    `json:"id"`
	BookID         string    `json:"book_id"`
	ChapterIndex   int64     `json:"chapter_index"`
	Title          string    `json:"title"`
	FilePath       string    `json:"file_path"`
	ParagraphCount int64     `json:"paragraph_count"`
	CreatedAt      time.Time `json:"created_at"`
}

type Paragraph struct {
	ID             string    `json:"id"`
	BookID         string    `json:"book_id"`
	ChapterIndex   int64     `json:"chapter_index"`
	ParagraphIndex int64     `json:"paragraph_index"`
	FilePath       string    `json:"file_path"`
	ContentPreview string    `json:"content_preview"`
	CreatedAt      time.Time `json:"created_at"`
}

type ParagraphEmbedding struct {
	ID          string    `json:"id"`
	ParagraphID string    `json:"paragraph_id"`
	BookID      string    `json:"book_id"`
	Embedding   []byte    `json:"embedding"`
	Dimensions  int64     `json:"dimensions"`
	Model       string    `json:"model"`
	CreatedAt   time.Time `json:"created_at"`
}

type ParagraphStat struct {
	BookID           string    `json:"book_id"`
	ChapterIndex     int64     `json:"chapter_index"`
	ParagraphIndex   int64     `json:"paragraph_index"`
	VisitCount       int64     `json:"visit_count"`
	IsSkipped        int64     `json:"is_skipped"`
	CustomFontFamily string    `json:"custom_font_family"`
	CustomFontSize   float64   `json:"custom_font_size"`
	IsBookmarked     int64     `json:"is_bookmarked"`
	UpvotesCount     int64     `json:"upvotes_count"`
	EmojiReactions   string    `json:"emoji_reactions"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Prompt struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Icon         string    `json:"icon"`
	ColorPalette string    `json:"color_palette"`
	SystemPrompt string    `json:"system_prompt"`
	UserPrompt   string    `json:"user_prompt"`
	Provider     string    `json:"provider"`
	Model        string    `json:"model"`
	Temperature  float64   `json:"temperature"`
	MaxTokens    int64     `json:"max_tokens"`
	IsBuiltin    int64     `json:"is_builtin"`
	IsEnabled    int64     `json:"is_enabled"`
	SortOrder    int64     `json:"sort_order"`
	Scope        string    `json:"scope"`
	BookID       string    `json:"book_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ReadingProgress struct {
	BookID                string    `json:"book_id"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            time.Time `json:"last_read_at"`
}

type SentenceAnnotation struct {
	SentenceHash   string    `json:"sentence_hash"`
	BookID         string    `json:"book_id"`
	ChapterIndex   int64     `json:"chapter_index"`
	ParagraphIndex int64     `json:"paragraph_index"`
	IsBookmarked   int64     `json:"is_bookmarked"`
	IsCollapsed    int64     `json:"is_collapsed"`
	HighlightColor string    `json:"highlight_color"`
	UpvotesCount   int64     `json:"upvotes_count"`
	EmojiReactions string    `json:"emoji_reactions"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type SentenceComment struct {
	ID           string    `json:"id"`
	SentenceHash string    `json:"sentence_hash"`
	BookID       string    `json:"book_id"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}
