// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Book struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Author          string    `json:"author"`
	Description     string    `json:"description"`
	Publisher       string    `json:"publisher"`
	Language        string    `json:"language"`
	CoverPath       string    `json:"cover_path"`
	SourceFilePath  string    `json:"source_file_path"`
	TotalChapters   int64     `json:"total_chapters"`
	TotalParagraphs int64     `json:"total_paragraphs"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Chapter struct {
	ID             string    `json:"id"`
	BookID         string    `json:"book_id"`
	ChapterIndex   int64     `json:"chapter_index"`
	Title          string    `json:"title"`
	FilePath       string    `json:"file_path"`
	ParagraphCount int64     `json:"paragraph_count"`
	CreatedAt      time.Time `json:"created_at"`
}

type Paragraph struct {
	ID             string    `json:"id"`
	BookID         string    `json:"book_id"`
	ChapterIndex   int64     `json:"chapter_index"`
	ParagraphIndex int64     `json:"paragraph_index"`
	FilePath       string    `json:"file_path"`
	ContentPreview string    `json:"content_preview"`
	CreatedAt      time.Time `json:"created_at"`
}

type ParagraphEmbedding struct {
	ID          string    `json:"id"`
	ParagraphID string    `json:"paragraph_id"`
	BookID      string    `json:"book_id"`
	Embedding   []byte    `json:"embedding"`
	Dimensions  int64     `json:"dimensions"`
	Model       string    `json:"model"`
	CreatedAt   time.Time `json:"created_at"`
}

type ReadingProgress struct {
	BookID                string    `json:"book_id"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            time.Time `json:"last_read_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}
