// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteEmbeddingsByBookID = `-- name: DeleteEmbeddingsByBookID :exec
DELETE FROM paragraph_embeddings WHERE book_id = ?
`

func (q *Queries) DeleteEmbeddingsByBookID(ctx context.Context, bookID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingsByBookID, bookID)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT 
    b.id, b.title, b.author, b.description, b.publisher, b.language, 
    b.cover_path, b.source_file_path, b.total_chapters, b.total_paragraphs,
    b.created_at, b.updated_at,
    CAST(COALESCE(p.current_chapter_index, 1) AS INTEGER) AS current_chapter_index,
    CAST(COALESCE(p.current_paragraph_index, 1) AS INTEGER) AS current_paragraph_index,
    CAST(COALESCE(p.percent_complete, 0.0) AS REAL) AS percent_complete,
    CAST(COALESCE(p.last_read_at, b.created_at) AS TEXT) AS last_read_at
FROM books b
LEFT JOIN reading_progress p ON b.id = p.book_id
WHERE b.id = ?
`

type GetBookByIDRow struct {
	ID                    string    `json:"id"`
	Title                 string    `json:"title"`
	Author                string    `json:"author"`
	Description           string    `json:"description"`
	Publisher             string    `json:"publisher"`
	Language              string    `json:"language"`
	CoverPath             string    `json:"cover_path"`
	SourceFilePath        string    `json:"source_file_path"`
	TotalChapters         int64     `json:"total_chapters"`
	TotalParagraphs       int64     `json:"total_paragraphs"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            string    `json:"last_read_at"`
}

func (q *Queries) GetBookByID(ctx context.Context, id string) (GetBookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.CoverPath,
		&i.SourceFilePath,
		&i.TotalChapters,
		&i.TotalParagraphs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentChapterIndex,
		&i.CurrentParagraphIndex,
		&i.PercentComplete,
		&i.LastReadAt,
	)
	return i, err
}

const getParagraphByID = `-- name: GetParagraphByID :one
SELECT id, book_id, chapter_index, paragraph_index, file_path, content_preview, created_at
FROM paragraphs
WHERE id = ?
`

func (q *Queries) GetParagraphByID(ctx context.Context, id string) (Paragraph, error) {
	row := q.db.QueryRowContext(ctx, getParagraphByID, id)
	var i Paragraph
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ChapterIndex,
		&i.ParagraphIndex,
		&i.FilePath,
		&i.ContentPreview,
		&i.CreatedAt,
	)
	return i, err
}

const getParagraphEmbedding = `-- name: GetParagraphEmbedding :one
SELECT id, paragraph_id, book_id, embedding, dimensions, model, created_at
FROM paragraph_embeddings
WHERE paragraph_id = ?
`

func (q *Queries) GetParagraphEmbedding(ctx context.Context, paragraphID string) (ParagraphEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getParagraphEmbedding, paragraphID)
	var i ParagraphEmbedding
	err := row.Scan(
		&i.ID,
		&i.ParagraphID,
		&i.BookID,
		&i.Embedding,
		&i.Dimensions,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT book_id, current_chapter_index, current_paragraph_index, percent_complete, last_read_at
FROM reading_progress
WHERE book_id = ?
`

func (q *Queries) GetProgress(ctx context.Context, bookID string) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, bookID)
	var i ReadingProgress
	err := row.Scan(
		&i.BookID,
		&i.CurrentChapterIndex,
		&i.CurrentParagraphIndex,
		&i.PercentComplete,
		&i.LastReadAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listBooks = `-- name: ListBooks :many
SELECT 
    b.id, b.title, b.author, b.description, b.publisher, b.language, 
    b.cover_path, b.source_file_path, b.total_chapters, b.total_paragraphs,
    b.created_at, b.updated_at,
    CAST(COALESCE(p.current_chapter_index, 1) AS INTEGER) AS current_chapter_index,
    CAST(COALESCE(p.current_paragraph_index, 1) AS INTEGER) AS current_paragraph_index,
    CAST(COALESCE(p.percent_complete, 0.0) AS REAL) AS percent_complete,
    CAST(COALESCE(p.last_read_at, b.created_at) AS TEXT) AS last_read_at
FROM books b
LEFT JOIN reading_progress p ON b.id = p.book_id
ORDER BY COALESCE(p.last_read_at, b.created_at) DESC
`

type ListBooksRow struct {
	ID                    string    `json:"id"`
	Title                 string    `json:"title"`
	Author                string    `json:"author"`
	Description           string    `json:"description"`
	Publisher             string    `json:"publisher"`
	Language              string    `json:"language"`
	CoverPath             string    `json:"cover_path"`
	SourceFilePath        string    `json:"source_file_path"`
	TotalChapters         int64     `json:"total_chapters"`
	TotalParagraphs       int64     `json:"total_paragraphs"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            string    `json:"last_read_at"`
}

func (q *Queries) ListBooks(ctx context.Context) ([]ListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.CoverPath,
			&i.SourceFilePath,
			&i.TotalChapters,
			&i.TotalParagraphs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentChapterIndex,
			&i.CurrentParagraphIndex,
			&i.PercentComplete,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByBookID = `-- name: ListChaptersByBookID :many
SELECT id, book_id, chapter_index, title, file_path, paragraph_count, created_at
FROM chapters
WHERE book_id = ?
ORDER BY chapter_index ASC
`

func (q *Queries) ListChaptersByBookID(ctx context.Context, bookID string) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chapter
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.ChapterIndex,
			&i.Title,
			&i.FilePath,
			&i.ParagraphCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParagraphEmbeddingsByBook = `-- name: ListParagraphEmbeddingsByBook :many
SELECT id, paragraph_id, book_id, embedding, dimensions, model, created_at
FROM paragraph_embeddings
WHERE book_id = ?
`

func (q *Queries) ListParagraphEmbeddingsByBook(ctx context.Context, bookID string) ([]ParagraphEmbedding, error) {
	rows, err := q.db.QueryContext(ctx, listParagraphEmbeddingsByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParagraphEmbedding
	for rows.Next() {
		var i ParagraphEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ParagraphID,
			&i.BookID,
			&i.Embedding,
			&i.Dimensions,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParagraphsByChapter = `-- name: ListParagraphsByChapter :many
SELECT id, book_id, chapter_index, paragraph_index, file_path, content_preview, created_at
FROM paragraphs
WHERE book_id = ? AND chapter_index = ?
ORDER BY paragraph_index ASC
`

type ListParagraphsByChapterParams struct {
	BookID       string `json:"book_id"`
	ChapterIndex int64  `json:"chapter_index"`
}

func (q *Queries) ListParagraphsByChapter(ctx context.Context, arg ListParagraphsByChapterParams) ([]Paragraph, error) {
	rows, err := q.db.QueryContext(ctx, listParagraphsByChapter, arg.BookID, arg.ChapterIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paragraph
	for rows.Next() {
		var i Paragraph
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.ChapterIndex,
			&i.ParagraphIndex,
			&i.FilePath,
			&i.ContentPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const upsertBook = `-- name: UpsertBook :exec
INSERT INTO books (
    id, title, author, description, publisher, language, 
    cover_path, source_file_path, total_chapters, total_paragraphs, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    author = excluded.author,
    description = excluded.description,
    publisher = excluded.publisher,
    language = excluded.language,
    cover_path = excluded.cover_path,
    total_chapters = excluded.total_chapters,
    total_paragraphs = excluded.total_paragraphs,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertBookParams struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Author          string `json:"author"`
	Description     string `json:"description"`
	Publisher       string `json:"publisher"`
	Language        string `json:"language"`
	CoverPath       string `json:"cover_path"`
	SourceFilePath  string `json:"source_file_path"`
	TotalChapters   int64  `json:"total_chapters"`
	TotalParagraphs int64  `json:"total_paragraphs"`
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) error {
	_, err := q.db.ExecContext(ctx, upsertBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.CoverPath,
		arg.SourceFilePath,
		arg.TotalChapters,
		arg.TotalParagraphs,
	)
	return err
}

const upsertChapter = `-- name: UpsertChapter :exec
INSERT INTO chapters (id, book_id, chapter_index, title, file_path, paragraph_count)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    file_path = excluded.file_path,
    paragraph_count = excluded.paragraph_count
`

type UpsertChapterParams struct {
	ID             string `json:"id"`
	BookID         string `json:"book_id"`
	ChapterIndex   int64  `json:"chapter_index"`
	Title          string `json:"title"`
	FilePath       string `json:"file_path"`
	ParagraphCount int64  `json:"paragraph_count"`
}

func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapter,
		arg.ID,
		arg.BookID,
		arg.ChapterIndex,
		arg.Title,
		arg.FilePath,
		arg.ParagraphCount,
	)
	return err
}

const upsertParagraph = `-- name: UpsertParagraph :exec
INSERT INTO paragraphs (id, book_id, chapter_index, paragraph_index, file_path, content_preview)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    file_path = excluded.file_path,
    content_preview = excluded.content_preview
`

type UpsertParagraphParams struct {
	ID             string `json:"id"`
	BookID         string `json:"book_id"`
	ChapterIndex   int64  `json:"chapter_index"`
	ParagraphIndex int64  `json:"paragraph_index"`
	FilePath       string `json:"file_path"`
	ContentPreview string `json:"content_preview"`
}

func (q *Queries) UpsertParagraph(ctx context.Context, arg UpsertParagraphParams) error {
	_, err := q.db.ExecContext(ctx, upsertParagraph,
		arg.ID,
		arg.BookID,
		arg.ChapterIndex,
		arg.ParagraphIndex,
		arg.FilePath,
		arg.ContentPreview,
	)
	return err
}

const upsertParagraphEmbedding = `-- name: UpsertParagraphEmbedding :exec
INSERT INTO paragraph_embeddings (id, paragraph_id, book_id, embedding, dimensions, model, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    embedding = excluded.embedding,
    dimensions = excluded.dimensions,
    model = excluded.model,
    created_at = CURRENT_TIMESTAMP
`

type UpsertParagraphEmbeddingParams struct {
	ID          string `json:"id"`
	ParagraphID string `json:"paragraph_id"`
	BookID      string `json:"book_id"`
	Embedding   []byte `json:"embedding"`
	Dimensions  int64  `json:"dimensions"`
	Model       string `json:"model"`
}

func (q *Queries) UpsertParagraphEmbedding(ctx context.Context, arg UpsertParagraphEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertParagraphEmbedding,
		arg.ID,
		arg.ParagraphID,
		arg.BookID,
		arg.Embedding,
		arg.Dimensions,
		arg.Model,
	)
	return err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO reading_progress (book_id, current_chapter_index, current_paragraph_index, percent_complete, last_read_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(book_id) DO UPDATE SET
    current_chapter_index = excluded.current_chapter_index,
    current_paragraph_index = excluded.current_paragraph_index,
    percent_complete = excluded.percent_complete,
    last_read_at = CURRENT_TIMESTAMP
`

type UpsertProgressParams struct {
	BookID                string  `json:"book_id"`
	CurrentChapterIndex   int64   `json:"current_chapter_index"`
	CurrentParagraphIndex int64   `json:"current_paragraph_index"`
	PercentComplete       float64 `json:"percent_complete"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.BookID,
		arg.CurrentChapterIndex,
		arg.CurrentParagraphIndex,
		arg.PercentComplete,
	)
	return err
}
