// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteEmbeddingsByBookID = `-- name: DeleteEmbeddingsByBookID :exec
DELETE FROM paragraph_embeddings WHERE book_id = ?
`

func (q *Queries) DeleteEmbeddingsByBookID(ctx context.Context, bookID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingsByBookID, bookID)
	return err
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts 
WHERE id = ? AND is_builtin = 0
`

func (q *Queries) DeletePrompt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePrompt, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT 
    b.id, b.title, b.author, b.description, b.publisher, b.language, 
    b.cover_path, b.source_file_path, b.total_chapters, b.total_paragraphs,
    b.created_at, b.updated_at,
    CAST(COALESCE(p.current_chapter_index, 1) AS INTEGER) AS current_chapter_index,
    CAST(COALESCE(p.current_paragraph_index, 1) AS INTEGER) AS current_paragraph_index,
    CAST(COALESCE(p.percent_complete, 0.0) AS REAL) AS percent_complete,
    CAST(COALESCE(p.last_read_at, b.created_at) AS TEXT) AS last_read_at
FROM books b
LEFT JOIN reading_progress p ON b.id = p.book_id
WHERE b.id = ?
`

type GetBookByIDRow struct {
	ID                    string    `json:"id"`
	Title                 string    `json:"title"`
	Author                string    `json:"author"`
	Description           string    `json:"description"`
	Publisher             string    `json:"publisher"`
	Language              string    `json:"language"`
	CoverPath             string    `json:"cover_path"`
	SourceFilePath        string    `json:"source_file_path"`
	TotalChapters         int64     `json:"total_chapters"`
	TotalParagraphs       int64     `json:"total_paragraphs"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            string    `json:"last_read_at"`
}

func (q *Queries) GetBookByID(ctx context.Context, id string) (GetBookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.CoverPath,
		&i.SourceFilePath,
		&i.TotalChapters,
		&i.TotalParagraphs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentChapterIndex,
		&i.CurrentParagraphIndex,
		&i.PercentComplete,
		&i.LastReadAt,
	)
	return i, err
}

const getParagraphByID = `-- name: GetParagraphByID :one
SELECT id, book_id, chapter_index, paragraph_index, file_path, content_preview, created_at
FROM paragraphs
WHERE id = ?
`

func (q *Queries) GetParagraphByID(ctx context.Context, id string) (Paragraph, error) {
	row := q.db.QueryRowContext(ctx, getParagraphByID, id)
	var i Paragraph
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ChapterIndex,
		&i.ParagraphIndex,
		&i.FilePath,
		&i.ContentPreview,
		&i.CreatedAt,
	)
	return i, err
}

const getParagraphEmbedding = `-- name: GetParagraphEmbedding :one
SELECT id, paragraph_id, book_id, embedding, dimensions, model, created_at
FROM paragraph_embeddings
WHERE paragraph_id = ?
`

func (q *Queries) GetParagraphEmbedding(ctx context.Context, paragraphID string) (ParagraphEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getParagraphEmbedding, paragraphID)
	var i ParagraphEmbedding
	err := row.Scan(
		&i.ID,
		&i.ParagraphID,
		&i.BookID,
		&i.Embedding,
		&i.Dimensions,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT book_id, current_chapter_index, current_paragraph_index, percent_complete, last_read_at
FROM reading_progress
WHERE book_id = ?
`

func (q *Queries) GetProgress(ctx context.Context, bookID string) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, bookID)
	var i ReadingProgress
	err := row.Scan(
		&i.BookID,
		&i.CurrentChapterIndex,
		&i.CurrentParagraphIndex,
		&i.PercentComplete,
		&i.LastReadAt,
	)
	return i, err
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT 
    id, name, description, icon, color_palette, system_prompt, user_prompt,
    provider, model, temperature, max_tokens, is_builtin, is_enabled, sort_order,
    scope, book_id, created_at, updated_at
FROM prompts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.ColorPalette,
		&i.SystemPrompt,
		&i.UserPrompt,
		&i.Provider,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.IsBuiltin,
		&i.IsEnabled,
		&i.SortOrder,
		&i.Scope,
		&i.BookID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listBooks = `-- name: ListBooks :many
SELECT 
    b.id, b.title, b.author, b.description, b.publisher, b.language, 
    b.cover_path, b.source_file_path, b.total_chapters, b.total_paragraphs,
    b.created_at, b.updated_at,
    CAST(COALESCE(p.current_chapter_index, 1) AS INTEGER) AS current_chapter_index,
    CAST(COALESCE(p.current_paragraph_index, 1) AS INTEGER) AS current_paragraph_index,
    CAST(COALESCE(p.percent_complete, 0.0) AS REAL) AS percent_complete,
    CAST(COALESCE(p.last_read_at, b.created_at) AS TEXT) AS last_read_at
FROM books b
LEFT JOIN reading_progress p ON b.id = p.book_id
ORDER BY COALESCE(p.last_read_at, b.created_at) DESC
`

type ListBooksRow struct {
	ID                    string    `json:"id"`
	Title                 string    `json:"title"`
	Author                string    `json:"author"`
	Description           string    `json:"description"`
	Publisher             string    `json:"publisher"`
	Language              string    `json:"language"`
	CoverPath             string    `json:"cover_path"`
	SourceFilePath        string    `json:"source_file_path"`
	TotalChapters         int64     `json:"total_chapters"`
	TotalParagraphs       int64     `json:"total_paragraphs"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	CurrentChapterIndex   int64     `json:"current_chapter_index"`
	CurrentParagraphIndex int64     `json:"current_paragraph_index"`
	PercentComplete       float64   `json:"percent_complete"`
	LastReadAt            string    `json:"last_read_at"`
}

func (q *Queries) ListBooks(ctx context.Context) ([]ListBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.CoverPath,
			&i.SourceFilePath,
			&i.TotalChapters,
			&i.TotalParagraphs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentChapterIndex,
			&i.CurrentParagraphIndex,
			&i.PercentComplete,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByBookID = `-- name: ListChaptersByBookID :many
SELECT id, book_id, chapter_index, title, file_path, paragraph_count, created_at
FROM chapters
WHERE book_id = ?
ORDER BY chapter_index ASC
`

func (q *Queries) ListChaptersByBookID(ctx context.Context, bookID string) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chapter
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.ChapterIndex,
			&i.Title,
			&i.FilePath,
			&i.ParagraphCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParagraphEmbeddingsByBook = `-- name: ListParagraphEmbeddingsByBook :many
SELECT id, paragraph_id, book_id, embedding, dimensions, model, created_at
FROM paragraph_embeddings
WHERE book_id = ?
`

func (q *Queries) ListParagraphEmbeddingsByBook(ctx context.Context, bookID string) ([]ParagraphEmbedding, error) {
	rows, err := q.db.QueryContext(ctx, listParagraphEmbeddingsByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParagraphEmbedding
	for rows.Next() {
		var i ParagraphEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ParagraphID,
			&i.BookID,
			&i.Embedding,
			&i.Dimensions,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParagraphsByChapter = `-- name: ListParagraphsByChapter :many
SELECT id, book_id, chapter_index, paragraph_index, file_path, content_preview, created_at
FROM paragraphs
WHERE book_id = ? AND chapter_index = ?
ORDER BY paragraph_index ASC
`

type ListParagraphsByChapterParams struct {
	BookID       string `json:"book_id"`
	ChapterIndex int64  `json:"chapter_index"`
}

func (q *Queries) ListParagraphsByChapter(ctx context.Context, arg ListParagraphsByChapterParams) ([]Paragraph, error) {
	rows, err := q.db.QueryContext(ctx, listParagraphsByChapter, arg.BookID, arg.ChapterIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paragraph
	for rows.Next() {
		var i Paragraph
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.ChapterIndex,
			&i.ParagraphIndex,
			&i.FilePath,
			&i.ContentPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT 
    id, name, description, icon, color_palette, system_prompt, user_prompt,
    provider, model, temperature, max_tokens, is_builtin, is_enabled, sort_order,
    scope, book_id, created_at, updated_at
FROM prompts
WHERE scope = 'global' OR (scope = 'book' AND book_id = ?)
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListPrompts(ctx context.Context, bookID string) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPrompts, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.ColorPalette,
			&i.SystemPrompt,
			&i.UserPrompt,
			&i.Provider,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.IsBuiltin,
			&i.IsEnabled,
			&i.SortOrder,
			&i.Scope,
			&i.BookID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDefaultPrompts = `-- name: ResetDefaultPrompts :exec
INSERT OR REPLACE INTO prompts (
    id, name, description, icon, color_palette, system_prompt, user_prompt,
    provider, model, temperature, max_tokens, is_builtin, is_enabled, sort_order,
    scope, book_id, created_at, updated_at
) VALUES 
(
    'prompt-explain',
    'Explain Nuance',
    'Explain literary nuances, historical/cultural context, and subtext of the selected paragraph',
    'Sparkles',
    'ruby',
    'You are a thoughtful reading companion and literary scholar. Analyze the selected text, illuminating subtext, historical/cultural context, metaphorical depth, and emotional resonance in clean, accessible markdown.',
    'Analyze and explain the context, subtext, and literary nuances of the following passage:\n\n{{text}}',
    '', '', 0.7, 2048, 1, 1, 1, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-summarize',
    'Quick Summary',
    'Summarize key ideas and narrative events in 1-2 punchy, concise sentences',
    'FileText',
    'amber',
    'You are an expert reading assistant. Distill the essence of the selected text into a punchy, accurate 1-2 sentence summary.',
    'Provide a concise 1-2 sentence summary capturing the essence of the following passage:\n\n{{text}}',
    '', '', 0.5, 1024, 1, 1, 2, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-vocabulary',
    'Vocabulary & Idioms',
    'Identify notable vocabulary words, archaic phrases, idioms, and literary expressions',
    'Languages',
    'teal',
    'You are a multilingual etymologist and linguist. Identify notable vocabulary words, archaic phrases, literary terms, or idioms from the text, explaining their definitions and nuances concisely.',
    'Identify key vocabulary, rare terms, or idioms in the following passage and explain their meanings:\n\n{{text}}',
    '', '', 0.3, 2048, 1, 1, 3, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-critic',
    'Literary Critique',
    'Critique prose style, pacing, tone, and author techniques',
    'Brain',
    'purple',
    'You are a perceptive literary critic. Critique the prose style, pacing, tone, and literary techniques employed by the author in this passage.',
    'Provide a critical review of the prose style, voice, tone, and narrative techniques in the following excerpt:\n\n{{text}}',
    '', '', 0.7, 2048, 1, 1, 4, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
`

func (q *Queries) ResetDefaultPrompts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDefaultPrompts)
	return err
}

const seedDefaultPrompts = `-- name: SeedDefaultPrompts :exec
INSERT OR IGNORE INTO prompts (
    id, name, description, icon, color_palette, system_prompt, user_prompt,
    provider, model, temperature, max_tokens, is_builtin, is_enabled, sort_order,
    scope, book_id, created_at, updated_at
) VALUES 
(
    'prompt-explain',
    'Explain Nuance',
    'Explain literary nuances, historical/cultural context, and subtext of the selected paragraph',
    'Sparkles',
    'ruby',
    'You are a thoughtful reading companion and literary scholar. Analyze the selected text, illuminating subtext, historical/cultural context, metaphorical depth, and emotional resonance in clean, accessible markdown.',
    'Analyze and explain the context, subtext, and literary nuances of the following passage:\n\n{{text}}',
    '', '', 0.7, 2048, 1, 1, 1, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-summarize',
    'Quick Summary',
    'Summarize key ideas and narrative events in 1-2 punchy, concise sentences',
    'FileText',
    'amber',
    'You are an expert reading assistant. Distill the essence of the selected text into a punchy, accurate 1-2 sentence summary.',
    'Provide a concise 1-2 sentence summary capturing the essence of the following passage:\n\n{{text}}',
    '', '', 0.5, 1024, 1, 1, 2, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-vocabulary',
    'Vocabulary & Idioms',
    'Identify notable vocabulary words, archaic phrases, idioms, and literary expressions',
    'Languages',
    'teal',
    'You are a multilingual etymologist and linguist. Identify notable vocabulary words, archaic phrases, literary terms, or idioms from the text, explaining their definitions and nuances concisely.',
    'Identify key vocabulary, rare terms, or idioms in the following passage and explain their meanings:\n\n{{text}}',
    '', '', 0.3, 2048, 1, 1, 3, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'prompt-critic',
    'Literary Critique',
    'Critique prose style, pacing, tone, and author techniques',
    'Brain',
    'purple',
    'You are a perceptive literary critic. Critique the prose style, pacing, tone, and literary techniques employed by the author in this passage.',
    'Provide a critical review of the prose style, voice, tone, and narrative techniques in the following excerpt:\n\n{{text}}',
    '', '', 0.7, 2048, 1, 1, 4, 'global', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
`

func (q *Queries) SeedDefaultPrompts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedDefaultPrompts)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const upsertBook = `-- name: UpsertBook :exec
INSERT INTO books (
    id, title, author, description, publisher, language, 
    cover_path, source_file_path, total_chapters, total_paragraphs, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    author = excluded.author,
    description = excluded.description,
    publisher = excluded.publisher,
    language = excluded.language,
    cover_path = excluded.cover_path,
    total_chapters = excluded.total_chapters,
    total_paragraphs = excluded.total_paragraphs,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertBookParams struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Author          string `json:"author"`
	Description     string `json:"description"`
	Publisher       string `json:"publisher"`
	Language        string `json:"language"`
	CoverPath       string `json:"cover_path"`
	SourceFilePath  string `json:"source_file_path"`
	TotalChapters   int64  `json:"total_chapters"`
	TotalParagraphs int64  `json:"total_paragraphs"`
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) error {
	_, err := q.db.ExecContext(ctx, upsertBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.CoverPath,
		arg.SourceFilePath,
		arg.TotalChapters,
		arg.TotalParagraphs,
	)
	return err
}

const upsertChapter = `-- name: UpsertChapter :exec
INSERT INTO chapters (id, book_id, chapter_index, title, file_path, paragraph_count)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    file_path = excluded.file_path,
    paragraph_count = excluded.paragraph_count
`

type UpsertChapterParams struct {
	ID             string `json:"id"`
	BookID         string `json:"book_id"`
	ChapterIndex   int64  `json:"chapter_index"`
	Title          string `json:"title"`
	FilePath       string `json:"file_path"`
	ParagraphCount int64  `json:"paragraph_count"`
}

func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapter,
		arg.ID,
		arg.BookID,
		arg.ChapterIndex,
		arg.Title,
		arg.FilePath,
		arg.ParagraphCount,
	)
	return err
}

const upsertParagraph = `-- name: UpsertParagraph :exec
INSERT INTO paragraphs (id, book_id, chapter_index, paragraph_index, file_path, content_preview)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    file_path = excluded.file_path,
    content_preview = excluded.content_preview
`

type UpsertParagraphParams struct {
	ID             string `json:"id"`
	BookID         string `json:"book_id"`
	ChapterIndex   int64  `json:"chapter_index"`
	ParagraphIndex int64  `json:"paragraph_index"`
	FilePath       string `json:"file_path"`
	ContentPreview string `json:"content_preview"`
}

func (q *Queries) UpsertParagraph(ctx context.Context, arg UpsertParagraphParams) error {
	_, err := q.db.ExecContext(ctx, upsertParagraph,
		arg.ID,
		arg.BookID,
		arg.ChapterIndex,
		arg.ParagraphIndex,
		arg.FilePath,
		arg.ContentPreview,
	)
	return err
}

const upsertParagraphEmbedding = `-- name: UpsertParagraphEmbedding :exec
INSERT INTO paragraph_embeddings (id, paragraph_id, book_id, embedding, dimensions, model, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    embedding = excluded.embedding,
    dimensions = excluded.dimensions,
    model = excluded.model,
    created_at = CURRENT_TIMESTAMP
`

type UpsertParagraphEmbeddingParams struct {
	ID          string `json:"id"`
	ParagraphID string `json:"paragraph_id"`
	BookID      string `json:"book_id"`
	Embedding   []byte `json:"embedding"`
	Dimensions  int64  `json:"dimensions"`
	Model       string `json:"model"`
}

func (q *Queries) UpsertParagraphEmbedding(ctx context.Context, arg UpsertParagraphEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertParagraphEmbedding,
		arg.ID,
		arg.ParagraphID,
		arg.BookID,
		arg.Embedding,
		arg.Dimensions,
		arg.Model,
	)
	return err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO reading_progress (book_id, current_chapter_index, current_paragraph_index, percent_complete, last_read_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(book_id) DO UPDATE SET
    current_chapter_index = excluded.current_chapter_index,
    current_paragraph_index = excluded.current_paragraph_index,
    percent_complete = excluded.percent_complete,
    last_read_at = CURRENT_TIMESTAMP
`

type UpsertProgressParams struct {
	BookID                string  `json:"book_id"`
	CurrentChapterIndex   int64   `json:"current_chapter_index"`
	CurrentParagraphIndex int64   `json:"current_paragraph_index"`
	PercentComplete       float64 `json:"percent_complete"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.BookID,
		arg.CurrentChapterIndex,
		arg.CurrentParagraphIndex,
		arg.PercentComplete,
	)
	return err
}

const upsertPrompt = `-- name: UpsertPrompt :exec
INSERT INTO prompts (
    id, name, description, icon, color_palette, system_prompt, user_prompt,
    provider, model, temperature, max_tokens, is_builtin, is_enabled, sort_order,
    scope, book_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    icon = excluded.icon,
    color_palette = excluded.color_palette,
    system_prompt = excluded.system_prompt,
    user_prompt = excluded.user_prompt,
    provider = excluded.provider,
    model = excluded.model,
    temperature = excluded.temperature,
    max_tokens = excluded.max_tokens,
    is_enabled = excluded.is_enabled,
    sort_order = excluded.sort_order,
    scope = excluded.scope,
    book_id = excluded.book_id,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPromptParams struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	Icon         string  `json:"icon"`
	ColorPalette string  `json:"color_palette"`
	SystemPrompt string  `json:"system_prompt"`
	UserPrompt   string  `json:"user_prompt"`
	Provider     string  `json:"provider"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int64   `json:"max_tokens"`
	IsBuiltin    int64   `json:"is_builtin"`
	IsEnabled    int64   `json:"is_enabled"`
	SortOrder    int64   `json:"sort_order"`
	Scope        string  `json:"scope"`
	BookID       string  `json:"book_id"`
}

func (q *Queries) UpsertPrompt(ctx context.Context, arg UpsertPromptParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrompt,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.ColorPalette,
		arg.SystemPrompt,
		arg.UserPrompt,
		arg.Provider,
		arg.Model,
		arg.Temperature,
		arg.MaxTokens,
		arg.IsBuiltin,
		arg.IsEnabled,
		arg.SortOrder,
		arg.Scope,
		arg.BookID,
	)
	return err
}
